version: "3.9"
services:
  db:
    image: pgvector/pgvector:pg17
    container_name: vuln_rag_pgvector
    ports:
      - "54320:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-rag_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-rag_pass}
      POSTGRES_DB: ${POSTGRES_DB:-rag_db}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata: